name: GTSFM Wheel Builder CI

on: [workflow_dispatch]

jobs:
  test_and_build:
    name: ${{ matrix.os }}_py${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python_version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v6.0.1
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
      - name: Set up Python
        run: uv python install ${{ matrix.python_version }}

      - name: Install pypa/build.
        run: uv pip install build --system

      - name: Build a binary wheel and a source tarball.
        run: |
          python -m build --sdist --wheel --outdir wheelhouse/ .

      - name: Archive wheels
        uses: actions/upload-artifact@v5
        with:
          name: wheels-${{ matrix.python_version }}-${{ matrix.os }}
          path: ./wheelhouse
