name: Reproducibility tests

on: [pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  run-repro-tests:
    name: Run reproducibility tests for different algorithms
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.1
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
      - name: Set up Python
        run: uv python install 3.10
      - name: Install dependencies
        run: |
          uv sync --extra dev --extra cpu
          uv pip install -e .
      - name: Environment setup
        run: |
          bash .github/scripts/setup.sh
      - name: Reproducibility tests
        run: |
          uv run pytest tests/repro_tests
